services:
  # 🛡️ Gluetun VPN Container (ProtonVPN via WireGuard)
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN  # Required for VPN networking (allows container to modify network settings)
    devices:
      - /dev/net/tun:/dev/net/tun  # Enables the VPN tunnel for secure traffic routing
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Disable IPv6 (recommended for VPN security)

    environment:
      - VPN_SERVICE_PROVIDER=protonvpn  # Using ProtonVPN as the provider
      - VPN_TYPE=wireguard  # WireGuard for faster, more secure VPN
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}  # Private key for VPN authentication
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-United Kingdom}  # Default country (UK)
      - SERVER_CITIES=${SERVER_CITIES:-London}  # Default city (London)
      - VPN_PORT_FORWARDING=on  # Enable port forwarding (required for better torrenting)
      - TZ=${TZ:-Europe/London}  # Timezone configuration

      # 🔒 Secure the Gluetun control API (used for dynamic port forwarding updates)
      - HTTP_CONTROL_SERVER=on
      - HTTP_CONTROL_SERVER_USER=${GLUETUN_USER:-admin}  # Default user (change this!)
      - HTTP_CONTROL_SERVER_PASSWORD=${GLUETUN_PASS:-securepassword}  # Default password (change this!)

    volumes:
      - ./gluetun:/gluetun  # Persist Gluetun VPN config (logs, server lists, etc.)

    ports:
      - "8080:8080/tcp"  # Maps qBittorrent Web UI (localhost:8080 → container:8080)

  # 🔄 qBittorrent - Torrent Client running inside VPN
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"  # Routes all traffic through the VPN container
    depends_on:
      gluetun:
        condition: service_healthy  # Ensures VPN is active before qBittorrent starts

    environment:
      - PUID=${PUID:-1000}  # User ID (set to match your system user)
      - PGID=${PGID:-1000}  # Group ID (set to match your system user)
      - TZ=${TZ:-Europe/London}  # Timezone
      - WEBUI_PORT=8080  # Port for the Web UI (inside the container)
      - QBITTORRENT_INTERFACE=tun0  # Ensures qBittorrent only uses VPN
      - DOCKER_MODS=ghcr.io/t-anc/gsp-qbittorent-gluetun-sync-port-mod:main  # Mod for automatic port sync
      - GSP_GTN_API_KEY=${GSP_GTN_API_KEY:-randomapikey}  # API key for port forwarding
      - GSP_QBITTORRENT_PORT=${GSP_QBITTORRENT_PORT:-53764}  # Port used for torrenting
      - GSP_MINIMAL_LOGS=false  # Enable full logs for debugging

    volumes:
      - ./qbittorrent:/config  # Stores qBittorrent settings & torrents
      - <YOUR_DOWNLOAD_PATH>:/downloads  # Replace with your local downloads directory
